// Reads src/diff.json and prints a markdown PR body to stdout.
// Used by the sync-and-update workflow: --body "$(node scripts/pr-body.js)"
//
// Usage: node scripts/pr-body.js

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const diffPath = path.join(__dirname, '../src/diff.json');
const metaPath = path.join(__dirname, '../src/source/sync-meta.json');

if (!fs.existsSync(diffPath)) {
  console.log('No diff.json found.');
  process.exit(0);
}

const report = JSON.parse(fs.readFileSync(diffPath, 'utf8'));
const locales = Object.keys(report);

const meta = fs.existsSync(metaPath)
  ? JSON.parse(fs.readFileSync(metaPath, 'utf8'))
  : null;

const lines = [];

lines.push('## Translation sync');
lines.push('');

if (meta?.actor) {
  const repoLink = meta.repo
    ? `[\`${meta.repo}\`](https://github.com/${meta.repo}/commit/${meta.sha ?? ''})`
    : 'a wallet app';
  lines.push(`Triggered by @${meta.actor} via ${repoLink}.`);
  lines.push('');
}

lines.push(
  'English keys have changed. This PR updates all language files to match. ' +
    'Empty-string values need to be translated before merging.',
);
lines.push('');

// Summary table
lines.push('| Language | Added | Removed | Needs translation |');
lines.push('|----------|------:|--------:|------------------:|');

for (const locale of locales) {
  const { added, removed } = report[locale];
  lines.push(`| \`${locale}\` | ${added.length} | ${removed.length} | ${added.length} |`);
}

// Per-language detail
for (const locale of locales) {
  const { added, removed } = report[locale];
  if (added.length === 0 && removed.length === 0) {
    continue;
  }

  lines.push('');
  lines.push(`### \`${locale}\``);

  if (added.length > 0) {
    lines.push('');
    lines.push(`**Added (${added.length}) — needs translation:**`);
    for (const key of added) {
      lines.push(`- \`${key}\``);
    }
  }

  if (removed.length > 0) {
    lines.push('');
    lines.push(`**Removed (${removed.length}):**`);
    for (const key of removed) {
      lines.push(`- \`${key}\``);
    }
  }
}

lines.push('');
lines.push('---');
lines.push('*Generated by [wallet-translations](https://github.com/rehive/wallet-translations) sync workflow.*');

console.log(lines.join('\n'));
