// Merges the per-app translation files into the combined src/language-en.json.
//
// Inputs (committed to this repo by CI from each wallet app):
//   src/source/wallet-react.json         — generated by wallet-react/languageSyncSelf.cjs
//   src/source/wallet-react-native.json  — generated by wallet-react-native/languageSync.cjs
//
// Output:
//   src/language-en.json          — merged result (web keys win on conflict)
//
// Usage:
//   yarn sync

const path = require('path');
const fs = require('fs');

function isObject(item) {
  return item && typeof item === 'object' && !Array.isArray(item);
}

function mergeDeep(target, ...sources) {
  if (!sources.length) {
    return target;
  }
  const source = sources.shift();

  if (isObject(target) && isObject(source)) {
    for (const key in source) {
      if (isObject(source[key])) {
        if (!target[key]) {
          Object.assign(target, { [key]: {} });
        }
        mergeDeep(target[key], source[key]);
      } else {
        Object.assign(target, { [key]: source[key] });
      }
    }
  }

  return mergeDeep(target, ...sources);
}

const root = path.join(__dirname, '..');
const webPath = path.join(root, 'src', 'source', 'wallet-react.json');
const mobilePath = path.join(root, 'src', 'source', 'wallet-react-native.json');
const outPath = path.join(root, 'src', 'language-en.json');

console.log('Syncing language files...');

const webData = fs.existsSync(webPath)
  ? JSON.parse(fs.readFileSync(webPath, 'utf8'))
  : {};

const mobileData = fs.existsSync(mobilePath)
  ? JSON.parse(fs.readFileSync(mobilePath, 'utf8'))
  : {};

console.log(`  web modules:    ${Object.keys(webData).length}`);
console.log(`  mobile modules: ${Object.keys(mobileData).length}`);

// Mobile is the base; web keys win on conflict
const merged = mergeDeep(mobileData, webData);

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(merged, null, 2));

console.log(`\nDone → ${outPath}`);
